### ISSUE TITLE
Feature Request: Add the ability to hide participant list in scheduled meetings

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#101]
Currently, all the participants you add to a scheduled meeting are visible in the email message that's sent out:
![Screen Shot 2020-07-24 at 8 10 33 AM](https://user-images.githubusercontent.com/9301423/88389792-2860d300-cd85-11ea-872d-f6920b57fca0.png)

A Basic user has requested the option to hide the participants so that they don't get to see the email addresses from all the other viewers.

Workaround: do not add any participants, the presenter manually forwards the scheduled meeting invite that they receive using the bcc field to mask recipients' email addresses

**Comment by LeahW** [comment]
I only received the meeting invite as the presenter when testing on stage. This is what the presenter's ics shows:
![Screen Shot 2020-07-29 at 9 26 15 AM](https://user-images.githubusercontent.com/9301423/88805772-93434d00-d17d-11ea-978c-2c80d0047b91.png)

**Comment by tuyentruong** [comment]
@LeahW on staging, we only send emails out to screenleap.com addresses. Other addresses won't get sent. I've updated staging to also send out emails to user accounts where admin has been set to true so we can do that for your other email address so you can receive the email.

**Comment by LeahW** [comment]
Confirmed that non-host ics invites are not showing the participant list
