### ISSUE TITLE
Feature Request: Do not close new meeting dialog screen if you click outside of it

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#104]
Steps to Reproduce:

1. Sign in to www.screenleap.com
2. Click 'Schedule meeting'
3. Click outside of dialog box for meeting details, it will close the box without saving anything that has been typed

![Screen Shot 2021-01-11 at 8 30 29 AM](https://user-images.githubusercontent.com/9301423/104188472-45e33100-53e7-11eb-88ea-0850444b2c24.png)

**Comment by tuyentruong** [comment]
Fixed by Screenleap/screenleap@dd53e9ae8ee203a190c3f39648537aab87f10fb7

**Comment by LeahW** [comment]
Confirmed fixed on prod
