### ISSUE TITLE
Feature Request: allow time zone to be specified in 'Create new meeting' screen

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#20]
Impact: the Meetings feature available in Pro subscription version of presenter app 

Description: While logged in to a Pro account, if you click on the Meetings menu and create a new meeting you can fill out a date and time but there's no way to specify which time zone. Feature request is to add the ability to specify which time zone.

**Comment by tuyentruong** [comment]
User should just edit their settings with the time zone they want to use.
