### ISSUE TITLE
Viewer image enlarged after upgrading iPad to latest iOS

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#21]
Impact: iPad Air2 64 gb with Retina display (9.0 13a 344 model #md512ll/a) when upgraded to iOS 9.0.2
Internet Explorer and Safari browsers.

Description: iPads could view screen shares normally until they were upgraded to the latest iOS 9.0.2, but now display an image that is enlarged to the point of being unusable as viewing screens. 

![ipadissue](https://cloud.githubusercontent.com/assets/9301423/10521544/63662a32-733e-11e5-92b7-3fcbcba3ad16.png)

Workaround: None. When viewers are asked to try toggling 'Fit to window' or 'Actual size' they either can't get to dropdown or 'screen we are sharing pops up but almost immediately ends with an error:  A problem occurred with this webpage so it was reloaded'

Additional notes: The user agent string captured in our Admin logs for the affected viewers is: Mozilla/5.0 (iPad; CPU OS 9_0_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13A452 Safari/601.1
Per user, "It only happens when I'm using Screenleap.  All other websites look normal."

**Comment by tuyentruong** [comment]
@LeahW Can you test if this is fixed for you on staging?

**Comment by LeahW** [comment]
As near as I can test using iPhone/Safari, it seems better.
Default view on production:
![photo oct 31 10 44 50 am](https://cloud.githubusercontent.com/assets/9301423/10864273/41f9fce2-7fbf-11e5-8171-8baac4917a71.png)

Default view on staging:
![photo oct 31 10 56 14 am](https://cloud.githubusercontent.com/assets/9301423/10864274/53ae6ad6-7fbf-11e5-984a-e4b031637008.png)

**Comment by LeahW** [comment]
This is still being reported by users, so I am re-opening the issue. Below are the Support tickets, affected user agent strings with screen size, and example share codes:

Support reference: 1771014141
User agent:Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko)  Version/9.0 Mobile/13G36 Safari/601.1
Screen size: 768 x 1024
Share code: 755614595

Support reference: 1629084532
User agent: Mozilla/5.0 (iPad; CPU OS 9_2_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13D15 Safari/601.1
Screen size: 768 x 1024
Share code: 264989224

Support reference: 1554181424
User agent: Mozilla/5.0 (iPad; CPU OS 9_2_1 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/48.0.2564.87 Mobile/13D15 Safari/601.1.46
Screen size: 768 x 1024
Share code: 605986010

Support reference: 149405082
User agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Screen size: 768 x 1024
Share code: 365906271

Support reference: 1488053519
User agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Screen size: 768 x 1024
Share code: 864051668

Support reference: 147815488
User agent: Mozilla/5.0 (iPad; CPU OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
Screen size: 768 x 1024
Share code: 495708296

**Comment by tuyentruong** [comment]
@LeahW Is this still an issue?

**Comment by LeahW** [comment]
We've had no recent reports of this issue to support. Additionally, one user told us she could again see the entire screen after upgrading her iPad to the new iOS version 10.0.
