### ISSUE TITLE
Feature Request: Default to last size and position of viewport, even on multiple monitors

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#22]
Impact: Mac Native, Win Native presenter apps

Description: The viewport will not return to the last position and size on subsequent screen shares if it was last used on a secondary monitor screen in a multi-monitor setup. It goes back to a position on the primary monitor. Request is to always retain the default size and position of the viewport.

**Comment by tuyentruong** [comment]
@LeahW Uladzimir tested this and it seems to appear correctly on multiple monitors with the rectangle on both monitors. He also testing quitting the app between screen shares. Can you follow up with the person to see what he might be doing differently? Does he sometimes use one monitor and sometimes 2 monitors?

**Comment by LeahW** [comment]
Per user: 
"Yes, the monitors stay in the same configuration. The three monitors are extended to form one large desktop.
I plug in the same way every day at work. At home, it’s the wild west… no extra monitor, sometimes an ipad as a second screen, sometimes two additional monitors."

**Comment by tuyentruong** [comment]
For the Mac app, I've confirmed that the app remembers that its rectangle is on the second monitor if you don't restart the Mac app between screen shares, but it reverts to the primary monitor if you restart the Mac app between screen shares.

**Comment by tuyentruong** [comment]
Confirmed that the Windows app works as expected both with and without restarting the Windows app between screen shares.
