### ISSUE TITLE
Feature Request: keep Chat window visible if in use

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#25]
Impact: All presenter apps

Description: The Chat feature only works when on the initial 'Your Screen is shared' webpage; if you navigate to a different page or have another browser window active it can no longer be used. Customer would like the Chat to stay on top if activated, perhaps attached to the control panel, so clients can chat while looking at a screen share of the company's webpage.

Workaround: They can use Yahoo messenger, etc. but that requires client log in to that service first

**Comment by tuyentruong** [comment]
User should open a new tab if they want to navigate to another page.
