### ISSUE TITLE
Chrome extension loses connection, needs to be re-loaded

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#26]
Impact: Reproducible on Win 7 PC using Chrome extension with both Free and Premium accounts

Steps to Reproduce: 
1. Click on Chrome extension and start a share/broadcast of browser or screen (occurs using any option)
2. Screen share can be viewed by viewer and seems to work as long as presenter is active.
3. Leave presenter screen idle for a few minutes (should take less than 5).
4. Screenleap extension icon disappears from address bar on presenter screen, although green rectangle remains if in browser mode. If you go to Chrome menu > Settings > Extensions you see this:
![extensions](https://cloud.githubusercontent.com/assets/9301423/11037926/712ca71a-86ce-11e5-9ae2-640b29234aea.png)

Eventually, presenter's share code instructions page re-directed to "Your screen share has ended.
We lost the connection to your computer. Please check your internet connection and refresh the page to try to resume the screen share." error page on Screenleap website

Viewer screen no longer updates and will eventually show 'The screen share you are viewing has ended'

Workaround: Win native

**Comment by tuyentruong** [comment]
I haven't been able to reproduce this. It is happening consistently for you? Do I need to be viewing the screen share as well?

**Comment by LeahW** [comment]
I've had it occur with or without viewers. It was more consistent yesterday; today after a fresh restart of the computer I couldn't get it to happen until I started opening more apps on the PC: PowerPoint, Skype, a few different browser windows with multiple tabs. I'll keep testing to see if there's a magic combination that makes it consistent

**Comment by tuyentruong** [comment]
Is this on Windows or Mac? If PC, how much memory do you have on your PC?

**Comment by LeahW** [comment]
This issue has been reported mostly by Win 7 users. I used a Win 7 Home Premium pc with only 2 GB installed memory. I've added some virtual memory, I think that's another 2 GB

**Comment by tuyentruong** [comment]
That's likely the same issue that the Chromebook users are experiencing.
I'm going to try to add some memory profiling support to the Chrome
extension to see if we can prevent the memory from running out (and the
resultant crash from happening).

On Tue, Nov 10, 2015 at 10:45 AM, Leah Williamson notifications@github.com
wrote:

> This issue has been reported mostly by Win 7 users. I used a Win 7 Home
> Premium pc with only 2 GB installed memory. I've added some virtual memory,
> I think that's another 2 GB
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Screenleap/support/issues/26#issuecomment-155527461.

## 

Tuyen Truong, CEO & Founder
Screenleap, Inc.
540 University Ave, Suite 250
Palo Alto, CA 94301
tuyen@screenleap.com

Screen sharing with installation-free viewing on all devices:
http://www.screenleap.com

**Comment by tuyentruong** [comment]
Unfortunately, the Chrome browser extension does not support inspecting the system memory. Whenever someone reports a crash while using the browser extension, we should ask them how much memory they have. The minimum seems to be 4GB.
