### ISSUE TITLE
Idle screen share prompt (no viewers for last 15 min) even on user's first screen share

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#27]
Impact: Not signed in, Free account, and Basic subscription users with the following User Agent string:
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
Can be reproduced on Production or Stage

Steps to Reproduce: 
1. Using User-Agent switcher extension for Chrome, set User Agent string to:
   Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
2. Start a new screen share, from either Free, Basic, or not-signed in user
3. Screen share starts, but you immediately see this prompt:
   ![idlescreenshare](https://cloud.githubusercontent.com/assets/9301423/11185333/48047936-8c4a-11e5-8e77-e6e15415a354.png)

Workaround: Click 'Continue Sharing' on prompt

Additional information: This happens on subsequent screen shares (and broadcasts) for the impacted users as well. Does not happen when using a Premium subscription login.

**Comment by tuyentruong** [comment]
This is likely because your plan hit the daily limit. Reinstalling the app won't remove the limit. If it happens again, we should wait 24 hours to see if the issue goes away.
