### ISSUE TITLE
Share code field is blank on 'Your screen is being shared' page 

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#28]
Impact: Mac native and Win native private shares, using any supported browser while signed in

Steps to Reproduce: 
1. On a Mac or Windows PC, go to www.screenleap.com
2. Sign in using any Screenleap user account
3. Click 'Share Privately'
4. Browser redirects to the 'Your screen is being shared' page, but the field which should contain 9 digit share code appears blank as in below screenshot:
   ![screen shot 2015-11-25 at 1 07 41 pm](https://cloud.githubusercontent.com/assets/9301423/11405423/98a1db7c-9375-11e5-9522-da936decd3fd.png)

Workaround: Use the 'Copy' button immediately to the right of the blank field and it will correctly copy the share code, or look at the control panel window or url link to obtain this info

**Comment by tuyentruong** [comment]
Will be fixed in December 2nd push
