### ISSUE TITLE
Cannot sign in to user account on Screenleap website

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#29]
Impact: Users signing in to the Screenleap website from Firefox web browser on a Mac running Mac OS X El Capitan version 10.11.1

Steps to Reproduce: 
1. Using Firefox  with Mac OS X El Capitan version 10.11.1 go to https://www.screenleap.com/
2. Click on Sign in
3. Enter any login and password and click 'Sign in'
4. Get redirected back to https://www.screenleap.com/ without being signed in

Additional notes: Mozilla developer console contains the following message after redirect in step 4:

"Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:3:0
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] d2e4kn0wu3avrd.cloudfront.net
Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

Workaround: Use Safari or Chrome to access Screenleap website or sign in from the Screenleap for Mac icon and launch screen share that way

**Comment by tuyentruong** [comment]
What version of Firefox are you using?

**Comment by LeahW** [comment]
Firefox version 42.0

**Comment by tuyentruong** [comment]
I am able to sign in successfully using Firefox 42 on 10.11.1. Anything
else that might be different?

On Mon, Nov 30, 2015 at 1:23 PM, Leah Williamson notifications@github.com
wrote:

> Firefox version 42.0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Screenleap/support/issues/29#issuecomment-160765958.

## 

Tuyen Truong, CEO & Founder
Screenleap, Inc.
540 University Ave, Suite 250
Palo Alto, CA 94301
tuyen@screenleap.com

Screen sharing with installation-free viewing on all devices:
http://www.screenleap.com

**Comment by LeahW** [comment]
Here's the troubleshooting info that Firefox provides:

## Application Basics

Name: Firefox
Version: 42.0
Build ID: 20151029151421
Update Channel: release
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:42.0) Gecko/20100101 Firefox/42.0
Multiprocess Windows: 0/1 (default: false)
Safe Mode: false

## Important Modified Preferences

browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 1
browser.download.importedFromSqlite: true
browser.places.smartBookmarksVersion: 7
browser.sessionstore.upgradeBackup.latestBuildID: 20151029151421
browser.startup.homepage_override.buildID: 20151029151421
browser.startup.homepage_override.mstone: 42.0
dom.apps.reset-permissions: true
dom.mozApps.used: true
extensions.lastAppVersion: 42.0
gfx.blacklist.direct2d: 3
media.gmp-gmpopenh264.abi: x86_64-gcc3-u-i386-x86_64
media.gmp-gmpopenh264.lastUpdate: 1447885088
media.gmp-gmpopenh264.version: 1.5.1
media.gmp-manager.buildID: 20151029151421
media.gmp-manager.lastCheck: 1448914123
network.auth.allow-subresource-auth: 2
network.cookie.prefsMigrated: true
network.http.atsvc.enabled: false
network.http.atsvc.oe: false
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1448914200
places.history.expiration.transient_current_max_pages: 104858
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 0
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1446815136

## Important Locked Preferences

## JavaScript

Incremental GC: true

## Accessibility

Activated: false
Prevent Accessibility: 0

## Library Versions

NSPR
Expected minimum version: 4.10.10
Version in use: 4.10.10

NSS
Expected minimum version: 3.19.4 Basic ECC
Version in use: 3.19.4 Basic ECC

NSSSMIME
Expected minimum version: 3.19.4 Basic ECC
Version in use: 3.19.4 Basic ECC

NSSSSL
Expected minimum version: 3.19.4 Basic ECC
Version in use: 3.19.4 Basic ECC

NSSUTIL
Expected minimum version: 3.19.4
Version in use: 3.19.4

## Experimental Features

**Comment by tuyentruong** [comment]
Is this still occurring?

**Comment by LeahW** [comment]
Yes, it still happens for me on https://www.screenleap.com/ (but not http://stage.screenleap.com/)

I'm on Firefox version 44.0.2
User agent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by LeahW** [comment]
Issue can be fixed by using the 'Refresh Firefox' button found here:
 https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

'Extensions and themes, website permissions, modified preferences, added search engines, download history, DOM storage, security certificate and device settings, download actions, plugin settings, toolbar customizations, user styles and social features will be removed.'
