### ISSUE TITLE
Customized message for 'Broadcast ended' is not being applied

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#30]
Impact: Pro or Premium accounts that use the 'Customize your broadcast page' option for 'Broadcast ended' with any presenter app

Steps to Reproduce:
1. Sign in or 'Sign In As' a Pro or Premium account
2. Click on 'Customize your broadcast page' link and Edit and set a 'Broadcast ended' custom message
3. Start a Broadcast
4. View the Broadcast
5. From the Presenter screen, click 'Stop Sharing'
6. Viewer is not redirected to the custom broadcast message.
7. Can go back to the 'Customize your broadcast page' settings and confirm the 'Broadcast ended' message is still set up

Workaround: none

**Comment by tuyentruong** [comment]
Fixed by Screenleap/screenleap@4281c14d57
