### ISSUE TITLE
No viewer pop-up when 'Always Show Audio Conferencing Information' checked

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#31]
Impact: All presenter apps; paid subscription users with 'Always Show Audio Conferencing Information' option checked in Settings & Preferences.

Steps to Reproduce:
1. In Settings & Preferences, check 'Always Show Audio Conferencing Information' and update
2. Start a new screen share or broadcast
3. Viewer connects, but does not see a pop-up indicating the dial-in numbers and conference id

Workaround:
Uncheck the option in your Settings & Preferences to 'Always Show Audio Conferencing Information' and then click 'Update' at the bottom of the page. The next time you share, you'll need to click the link to 'Show Instructions' under Audio Conferencing, but when you do it should give you a button to 'Show audio conference information to viewers'. Clicking this button will force a pop-up with the conference call information to display to viewers when they connect to your broadcast

**Comment by tuyentruong** [comment]
Fixed. Can you confirm on staing?

**Comment by LeahW** [comment]
Just confirmed it's fixed on stage for all browsers and presenter apps. Thanks!
