### ISSUE TITLE
Unable to start screen share, followed by Java troubleshooting page

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#33]
Impact: 
Win native users, with user agent strings of:
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
-or-
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

Description:
Users all had previously shared successfully using Win native, but starting on 12/21/15 were unable to start a screen share or broadcast. They would  be directed to a troubleshooting page telling them they did not have Java installed or needed to update Java. None of these users had the Java applet specified in their Settings & Preferences

Additional Information:
Affected user ids for investigation: 106042  105294  97120  93661

Workaround:
Complete uninstall of Screenleap for Windows, followed by reinstall of the latest version

**Comment by tuyentruong** [comment]
@LeahW I could only find support tickets saying they were redirected to the Java troubleshooting pages for 106042 and 93661. Are the other 2 users reporting the same issue?
