### ISSUE TITLE
Cancel sharing request on Mac native does not resume viewer screen

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#36]
Impact: Viewers on Mac Native who request to become a presenter, then cancel the sharing request

Steps to Reproduce:
1. Start a new screen share
2. View the screen share from a Mac
3. On Mac viewer screen, click 'Become presenter'
4. When prompted that you are waiting for the current presenter to approve request, click button on Mac to 'Cancel sharing request'
5. Mac screen reverts to 'We are enable to share your screen' troubleshooting page, rather than resuming viewing of the screen share

**Comment by tuyentruong** [comment]
I couldn't reproduce this on staging. Can you retry on staging?

**Comment by LeahW** [comment]
The troubleshooting page is not coming up on staging anymore. Now it resumes the screen share immediately if you didn't download the Mac app during the presenter swap request.  If you do download, it's possible to get stuck on the 'Loading screen' page if you cancel the sharing request and the current presenter has the prompt up on their screen to 'View other person's screen' or 'Continue sharing' . Once the current presenter confirms 'Continue sharing' it resumes the screen share. Other viewers continue to see the screen share without interruption, so I don't think it's an issue
