### ISSUE TITLE
User's shared screen does not load in Customer Support tool

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#37]
Impact: Screen shares launched from Customer Support tool using Mac or PC

Steps to Reproduce:
1. Log in as support@screenleap and 'Create new support session'
2. Go to support link from another computer. Asks you to select what to share and tells you that screen is shared.
3.  Receive notification that session has started in Customer Support tool and click to view screen share. Never get past 'Loading Screen' message

Workaround: Use the desktop app or another non-Customer Support account on the website to start a regular screen share and ask viewer to use the 'Become Presenter' button to swap roles with host

**Comment by tuyentruong** [comment]
Fixed by Screenleap/screenleap@97ad4287aa
