### ISSUE TITLE
Presenter still sees 'Your screen is shared' when connection has been lost

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#38]
Impact: Staged version of Win native

Steps to Reproduce:
1. Start a screen share from stage.screenleap.com
2. View the screen share
3. Turn off WiFi on presenting computer
4. The viewer eventually sees 'The screen share you are viewing has ended.' page, but the presenter never gets any indication that there is a problem. The control panel stays green and says 'Your screen is shared' even while connection is lost

**Comment by tuyentruong** [comment]
@LeahW Can you test on staging?

**Comment by LeahW** [comment]
The control panel now changes from green 'Your screen is shared' to the orange 'Reconnecting' message after about 2 minutes without internet connection

**Comment by LeahW** [comment]
It's switching between the orange and green messages now that I've turned the WiFi back on. And the viewer screen didn't recover or go to 'The screen share has ended' page, but just stayed frozen on last screen

**Comment by tuyentruong** [comment]
Also addresses issues in Screenleap/screenleap#5225
