### ISSUE TITLE
Visible branding on the beta browser extension for API

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#40]
Screenleap branding is visible on the the beta browser extension for API in the following areas:
1. When you first install the browser extension from https://www.screenleap.com/api/demo you are prompted to 'Add Screenleap' so branding is evident in the name of the extension
2. Installed browser share extension has the menu option 'Visit Screenleap site'
3. After starting a screen share from the browser extension, you are directed to a 'Your screen is shared' page containing a Screenleap url and directions to go to the www.screenleap.com site to enter the share code. Browser extension also shows Screenleap url if clicked on.
4. After share has ended, you are taken to a ' Your screen share has ended' page containing:
            Feedback
            How was Screenleap? Please give us your feedback
            Like Screenleap? Show us some love:
   
   With feedback mail to link and social media links.

**Comment by tuyentruong** [comment]
1. This can't be hidden.
   2-4. For right now, we don't have an API-specific version of the browser extension so the users will see the Screenleap branding when accessing the browser extension menu.

**Comment by tuyentruong** [comment]
Browser extension is being deprecated in favor of ifree so this won't be implemented.
