### ISSUE TITLE
First screen share from Microsoft Edge browser fails

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#41]
Impact: First time users launching a Win native screen share from Microsoft Edge browser.

Steps to Reproduce:
1. Download 'MSEdge on Win10' from https://dev.windows.com/en-us/microsoft-edge/tools/vms/mac/ and run in VirtualBox 
2. Open a new Edge browser window and go to www.screenleap.com
3. Click 'Share your screen now'
4. Follow prompts to install and run Win native app; it installs the desktop icon but the first screen share fails to launch even after using 'Click here'

Workaround: Repeat steps 2 and 3 or start a share from the installed desktop icon and it will launch the screen share successfully

**Comment by tuyentruong** [comment]
Are there any popups that you need to confirm on the initial installation?

**Comment by LeahW** [comment]
No longer reproducible on Win 10 / MS Edge Virtualbox
