### ISSUE TITLE
Unable to start 'native app' shares from API Demo page using Mac

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#42]
Impact: Confirmed issue on MacBook Air running OS X El Capitan 10.11.3 and a MacBook running OS X Yosemite 10.10.5. Affects Mac native app shares launched from API Demo page

Steps to Reproduce:
1. Remove any previously installed Screenleap apps, go to https://www.screenleap.com/api/demo
2. Presenter App type should be set to (default) option of 'Native app'
3. Green banner and white pop-up window appear indicating that the screen share is starting, but after a few minutes, a 'Service disruption' message comes up

Workaround: Can launch a screen share successfully if the presenter app is set to 'Browser extension' (may take up to 3 attempts if extension not already installed) or if using the non-API Mac native app accessed from www.screenleap.com main page

**Comment by LeahW** [comment]
Added log files from MacBook / OS X El Capitan 10.11.3

[screenshare.txt](https://github.com/Screenleap/support/files/184949/screenshare.txt)
[screenshareinst.txt](https://github.com/Screenleap/support/files/184950/screenshareinst.txt)

**Comment by tuyentruong** [comment]
There was another ScreenShare app on the Mac being tested on. Not a real issue.
