### ISSUE TITLE
Feature Request: Add Full Screen mode functionality to Viewer app

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#44]
Impact: All viewer apps

Description: Feature request is to add a 'Full Screen' mode option within the Viewer app. This should allow viewers to see only the screen share content, without the browser menu, address bar, Screenleap banner, etc., that normally appears. The Full Screen mode would be able to be toggled on or off as needed.

**Comment by tuyentruong** [comment]
Duplicated of fixed Screenleap/screenleap#6299
