### ISSUE TITLE
Chrome Extension Memory error

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#45]
Impact: Screen shares from the Chrome extension 

Steps to Reproduce: 
1. Share your screen privately (entire screen mode) using Stage extension https://stage.screenleap.com/browser-share
2. Have a viewer connect to session from another computer
3. Open Performance tab of Task manager (Windows) or Apple menu > About this Mac > Storage tab (Mac) to see memory usage statistics. Memory usage climbs towards 100% on PC and application memory errors with force quit prompts appear on Mac, followed by crash of screen share

**Comment by tuyentruong** [comment]
The object pool seems to have fixed the memory leak. Closing.
