### ISSUE TITLE
Crashes in Chrome Extension on Chrome OS

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#47]
Impact: Chrome extension shares from company id 3185 are crashing, with the extension becoming disabled when it happens

Description:
Shares are typically started from Gmail using Chrome OS on a Chromebook. Examples share codes:
803652732
078769840
679384862
469521278

> > > Update

ID: 25014 on version 15.5.8 of extension uses a vm with 4 GB of memory and 2 processors.   Says it happens only when screenleap sits idle while he is talking to client describing something (about 5-10 minutes) and thinks it may be related to running out of disk space

ID: 105757 on version 15.5.9 still experiencing crashes (008347564, 846715425, 783810641)

**Comment by tuyentruong** [comment]
@LeahW I pushed a new production version of the Chrome extension with some changes from the last week reverted. Can you have somone uninstall the Chrome extension and install this one to see if it fixes the crash issue him/her?

https://chrome.google.com/webstore/detail/screenleap/flphdbkbpmfdpihinpidbiahfkeibmed?authuser=4

**Comment by tuyentruong** [comment]
Fixed by commit Screenleap/screenleap@6b39c5d
