### ISSUE TITLE
Update website to remove obsolete references to applet and non-Chrome extensions

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#48]
Attached please find zip file containing track changes documents for all webpages that required updating. In addition to text changes, I also updated some of the images to reflect newer look of browser extension menu and Screenleap website.

[Screenleap Website Changes.zip](https://github.com/Screenleap/support/files/215374/Screenleap.Website.Changes.zip)

**Comment by tuyentruong** [comment]
@LeahW Looks great. Thanks!
