### ISSUE TITLE
Green rectangle not appearing or not loading properly

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#49]
Impact: Affecting several users at Company ID 79. Users report that "the “show in rectangle” option. Either it doesn’t show on the screen or wont load properly if you have it on that option"

See attached screenleap.log file (uploaded as .txt) for details.
[screenleapGreenRectangle.txt](https://github.com/Screenleap/support/files/219700/screenleapGreenRectangle.txt)

**Comment by tuyentruong** [comment]
@LeahW Did deleting the .screenleap file fix the issue for the user?

**Comment by LeahW** [comment]
Not only did it fix the issue for the user who they tried it for, the IT contact said "I noticed that all the previous users that had the same issue started working again this morning without me running these steps."

This was on April 15 and no further recurrences have been reported.

**Comment by tuyentruong** [comment]
Great. Yeah I pushed a fix for this and another issue over the weekend.
