### ISSUE TITLE
Bots appearing to be viewers

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#54]
Steps to Reproduce:
1. Start a screen share
2. Tweet the link and click on it -or- send it in a Skype message and click on it
3. Viewers with bot user agent strings join the screen share, counting against viewer limit and inflating viewer count

Example User Agent Strings:

Twitterbot/1.0

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.13 (KHTML, like Gecko) Chrome/30.0.1599.66 Safari/537.13 Luminator-ur/2.0

Google-HTTP-Java-Client/1.17.0-rc (gzip)

Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Applebot/0.1; +http://www.apple.com/go/applebot)

Mozilla/5.0 (Windows NT 6.1; WOW64) SkypeUriPreview Preview/0.5

**Comment by tuyentruong** [comment]
Discussed and best fix is probably to not count the viewer until the viewer page makes the initial connection to send the viewer info (v1).

**Comment by tuyentruong** [comment]
@LeahW Can you test on staging?

**Comment by LeahW** [comment]
The bot viewers still appear in Stage-Admin, but don't increment the viewer count seen by the presenter and don't prevent legitimate viewers from joining a share from a Free account. So I think the fix is successful!

If needed, here are some example share codes from stage testing: 862224882, 647422663, 233325668, 545284428
