### ISSUE TITLE
 'Hide pause button' and 'Hide screen toggle' not enforced on API 

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#58]
Impact: Native app API shares with 'Hide pause button' and 'Hide screen toggle' presenter options in use

Steps to Reproduce (Windows):
1.  Go to https://www.screenleap.com/api/demo from a PC
2. Select 'Native app'
3. Expand presenter options and check Hide pause button' and 'Hide screen toggle' 
4. Start screen share. It shows 'Screenleap' in console
5. End screen share
6. Quit Screen Share app from icon in system tray
7. Start another screen share without changing any of the options
8. 'Screenleap' branding, Pause button, and screen toggle all appear in console even though the options are still checked to hide these.

Steps to Reproduce (Mac):
1.  Go to https://www.screenleap.com/api/demo from a Mac
2. Select 'Native app'
3. Expand presenter options and check Hide pause button' and 'Hide screen toggle' 
4. Start screen share.
5. End screen share.
6. Start another screen share without changing any of the options
7. Either on the first or second screen share the 'Screenleap' branding, Pause button, and screen toggle will all appear in console even though the options are still checked to hide these.

**Comment by tuyentruong** [comment]
Fixed by updating API web servers
