### ISSUE TITLE
Screenleap branding shown on console for API Demo shares

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#59]
Impact: Screen shares from the API Demo page on a Mac using Chrome, Safari, or Firefox

Steps to Reproduce:
1. Delete all previous copies of Screenleap and Screenshare from Mac
2. Go to https://stage.screenleap.com/api/demo using Chrome, Safari, or Firefox
3. Sign in and start a new native app screen share with default presenter options. The 'Show Screenleap Branding' is not checked by default
4. Open and run ScreenShare-Stage.dmg to start sharing
5. Console that appears shows 'Screenleap' not 'Screen Share'

**Comment by tuyentruong** [comment]
I haven't been able to reproduce the issue.

What account are you using? What is the name of the company for the account? It should show the company name on the console.

**Comment by tuyentruong** [comment]
Works as intended.
