### ISSUE TITLE
Screenleap starts upon reboot, despite disabling auto-start

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#63]
Impact: Win native, confirmed on Win 10 and Win 7 OS
1. Install and run Screenleap on a Windows PC
2. Click on the system tray Screenleap icon and select 'Quit Screenleap'
3. Uncheck 'Auto-start Screenleap on computer startup'
4. Click on Quit
5. Shut down PC
6. Power on PC (Screenleap does not auto-start)
7. Launch Screenleap app
8. Click on the system tray Screenleap icon and select 'Quit Screenleap'
9. Auto-start Screenleap on computer startup' is already unchecked.
10. Click on Quit
11. Shut down PC
12. Power on PC (Screenleap auto-starts)

**Comment by LeahW** [comment]
Updating to include Win 7 in list of known, impacted operating systems

**Comment by ghost** [comment]
Fixed in istart branch(it based on i5245 branch).

**Comment by ghost** [comment]
Commit: https://github.com/Screenleap/screenleap/commit/e6df73a020a99f243f256eed0c7591a625775638
