### ISSUE TITLE
API freezing up and connection errors

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#65]
Impact: API shares from company id 651 are freezing up for presenter and/or preventing viewers from joining due to a 'connection error'. Reported by multiple users starting on 10/17/16

Example share codes: 523535530 (before initial fix attempt)  and 203752367 (after attempted fix)

**Comment by LeahW** [comment]
Additional info  and example share codes from customer:

"it is lagging, and then pausing and waiting for "presenter to connect" from the user side"

264884441
455934022

**Comment by LeahW** [comment]
Here's the log file from an affected user:

[APIuser.txt](https://github.com/Screenleap/support/files/536779/APIuser.txt)

**Comment by tuyentruong** [comment]
It looks like the presenter was unable to connect successfully in one of the screen shares. Let's wait and see if they experience any more issues in the coming days.

**Comment by tuyentruong** [comment]
This should be resolved now. It looks like the API web servers were not aware of the new server regions, which has been fixed.
