### ISSUE TITLE
Viewers only see 'Loading Screen' when trying to connect

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#66]
Impact: Several users at the same company can start Win native sessions, but their viewers are only seeing 'Loading screen' These presenters and viewers were able to share as of last week without issue. 

Example share codes: 
026914188
357274018
293388836
499120687
802880744
585195839

Log files attached
[Nscreenleap.txt](https://github.com/Screenleap/support/files/548986/Nscreenleap.txt)
[Nscreenleapinst.txt](https://github.com/Screenleap/support/files/548987/Nscreenleapinst.txt)
[Nscreenleapstart.txt](https://github.com/Screenleap/support/files/548989/Nscreenleapstart.txt)

**Comment by tuyentruong** [comment]
Fixed by Screenleap/screenleap@3336918bd, Screenleap/screenleap@49d3c291de, and Screenleap/screenleap@31514bfa6
