### ISSUE TITLE
Screen share launches but doesn't send data

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#67]
Description: A Premium customer who has been able to share successfully in the past with Win native now gets the green rectangle to appear, but viewers do not see that the broadcast has started. We've done a clean install since he was on an older version (11.6.2.0) and Admin confirms he is now on version 11.8.3.0, but the problem remains. Log files are attached:

[screenleap.txt](https://github.com/Screenleap/support/files/569575/screenleap.txt)
[screenleapinst.txt](https://github.com/Screenleap/support/files/569576/screenleapinst.txt)

**Comment by LeahW** [comment]
Customer has changed their HTML embed code to remove the '3536' from the broadcast link

This works to allow viewers to see the screen, but it introduced a logo in the upper left of the iframe and a 'Sign in' link in the upper right. He's now wondering how to get rid of these

**Comment by tuyentruong** [comment]
Closed by https://github.com/Screenleap/screenleap/commit/5ee8f3b4b730f666a26205e4accb491f923bb0c6
