### ISSUE TITLE
 'You do not have access to this screen share.' viewer error on API

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#68]
steps to reproduce the problem:

1) Goto: http://jobsupportservices.com/ and click "Share Screen" on the right side of the page
2) Click the "Start Sharing Now" button in the popup dialog

3) Goto: https://www.screenleap.com/ and login as william.harris@internetsearchconsultants.com

4) Type the code given to you in step 2 in "View Screen Share" and click "View Screen Share" button

5) You will get the error message "error message.png"

**Comment by tuyentruong** [comment]
If the user is using the API, their viewers cannot view a screen share by going to the Screenleap site and entering the share code. Instead, they need to use the viewerUrl that is returned when they created the screen share.
