### ISSUE TITLE
'Unsupported browser' warning on an IE11 string

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#71]
Steps to Reproduce:

1. Start a screen share

2. Emulate the following user-agent string:
 Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; NP06; rv:11.0) like Gecko and view the screen share

3. Receive the following warning:
"Unsupported Browser
Your browser is not currently supported for viewing a screen share.

We require at least version 9 for Internet Explorer. Please either upgrade your Internet Explorer browser or consider using a different browser such as Chrome or Firefox.

If you cannot switch browsers, click the button below to join the share anyway, understanding that it may not work."

**Comment by LeahW** [comment]
One user still reporting the issue with this IE11 user agent string:

Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by tuyentruong** [comment]
This has been fixed but it may require an update of the app servers in production to fix. Will push if necessary based on user feedback.
