### ISSUE TITLE
Meetings not starting in Win native or Mac native apps

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#72]
Impact: Mac native and Win native users without the browser share extension installed that use the 'Meetings' feature to start screen shares

Steps to Reproduce:

1. Sign in to a Pro or Premium account on www.screenleap.com
2. Click on Meetings
3. Create a new meeting for later today and save
4. Click 'Start' next to meeting
5. If the browser share extension is installed, meeting will start using the extension. However, if not installed, the meeting does not start. This happens whether the Mac or Windows native app is already installed or not.

**Comment by tuyentruong** [comment]
Not able to reproduce. Will reopen if happens again.
