### ISSUE TITLE
Implement 'Checking configuration' and Browser Share install prompt for API

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#73]
Steps to Reproduce:

1. Use Linux user agent without Screenleap extension installed
2. Go to https://www.screenleap.com/api/demo
3. Select the 'browser extension' presenter app
4. Start screen share
5. A 'Checking configuration' and Browser Share install prompt appears, allowing the user to install the extension. The screen share then immediately begins

API user would like to know what call is needed to accomplish step 5 outside of the API Demo page?

**Comment by tuyentruong** [comment]
Please see https://dev.screenleap.com/api/presenter for the new instructions for checking if extension is installed and installing the extension.
