### ISSUE TITLE
Feature Request: Create voice recording file if recording and audio conference used

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#74]
Impact: Premium customers using both recording and the dial-in audio conference features

Description: If customer dials in and uses Screenleap audio conferencing and has also enabled recording, the ability to create a recording of that audio conference is requested

**Comment by tuyentruong** [comment]
The audio is currently captured in the recording. We don't plan to support a separate audio file as it can be extracted from the MP4 recording using open source tools.
