### ISSUE TITLE
Feature request: redirect to deprecation notice on Java applet share attempt

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#76]
Users have noted the inability to use the Java applet. We should provide them with instructions to use the Chrome extension instead, if possible.

**Comment by tuyentruong** [comment]
@LeahW Can you test on staging?

**Comment by LeahW** [comment]
Looks good! Screen share attempts from a Firefox/Ubuntu user agent string will now trigger this alert:

Operating system and browser not supported
Unfortunately, Screenleap is not compatible with your operating system and browser.
We support sharing using the Chrome browser on your operating system.
If you think this is an error, please contact us for assistance.
