### ISSUE TITLE
Feature Request: Support multiple browser windows in iOS app

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#81]
Description: Currently, only the initial window that opens when you start an iOS share is shared. If you open a second window, for example using these steps:

1. Start broadcast from iOS app
2. Join viewer
3. Search for something on Google
4. Hold down your finger on any link until it opens in a new window

. . . content from the second window isn't seen by the viewer. If possible, the viewer should be able to see the active browser window if multiple windows are opened

**Comment by tuyentruong** [comment]
I'm going to fix this by opening in the same webview when a user tries to open a link in a new webview.
