### ISSUE TITLE
Feature request: Show active share codes for account on signed in Screenleap page

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#82]
A user has requested the ability to see if he is currently sharing privately, and if so, show the 9 digit share code somewhere on the signed in www.Screenleap.com page. This is so he can check to see if he is sharing and join the share from another computer, without being in front of the presenting computer. User does not want to use Broadcast mode for this use case.

**Comment by tuyentruong** [comment]
This is a rare use case. Not supporting.
