### ISSUE TITLE
Feature Request: Allow Administrators of Company accounts access to all Recordings

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#86]
Administrators of company accounts would like to be able to access and manage recordings for all users on the account. This should be something they can do on the signed-in website itself and will be used for training and QA purposes

**Comment by tuyentruong** [comment]
What do you mean by managing recordings? Just be able to view them? Filter on a specific user? Delete them? Something else? The more details the better.

**Comment by danieldechert** [comment]
Administrators need to be able to filter based on user and date. (eventually alphabetically when we put in the feature to rename the recordings) Admin also needs to have access to delete the recordings.

**Comment by LeahW** [comment]
The filtering by User isn't working for the Admin. This is what I see when I log in as the user (testagainscreen@mailinator.com) for that user's recorded shares:
![screen shot 2018-07-02 at 8 38 38 am](https://user-images.githubusercontent.com/9301423/42164414-f61c6344-7dd3-11e8-989d-d2a560d1df87.png)
And this is what I see for the same user's recorded shares when signed in as the Admin user (leah@screenleap.com):
![screen shot 2018-07-02 at 8 39 11 am](https://user-images.githubusercontent.com/9301423/42164460-15016d04-7dd4-11e8-845b-1545fba1eada.png)

Also, is it the intention to not show the share code field when looking at all users or a specific user other than the one logged in?
