### ISSUE TITLE
Prepare onboarding for Screenleap for Education solution

### ISSUE THREAD

**Issue by tuyentruong** [Screenleap/support#87]
* Figure out school start dates for each school in pilot
* Get in touch with the contact person when getting close to the start of the school year to let them know the pilot is ready
* Create Screenleap for Education accounts for the schools
* Give them an email that they can send to their teachers to recruit teachers for the pilot
* Contact the teachers that have volunteered for the pilot and make sure their accounts are set up
* Assist teachers with importing classes and students
* Make sure the teachers are able to successfully use the Education solution

**Comment by LeahW** [comment]
Sample pilot letter. Please let me know any feedback or changes needed!
>>>>>>

Dear {education lead}, 

Screenleap is pilot-testing a screen and audio sharing application called Screenleap for Education that will help educators present and record lessons from their PCs, Macs, iPads, Chromebooks, SMART Boards, Android devices, and more. These lessons can then be viewed by students and other teachers from any web-enabled device, eliminating the need to re-teach lessons that students miss and allowing you to share recorded lessons with other teachers at your school. 

We hope Screenleap will help you save time, work more effectively, and at the same time reduce IT administration needs by not having to maintain software on the student’s computer or device. We are looking for volunteer educators to help evaluate Screenleap and then provide us feedback about your experience. Similar pilots in other organizations show that most people have a positive experience, but we want to be sure that Screenleap meets the needs of your unique educational environment. If you would be interested in participating in this free pilot program and providing feedback on Screenleap for Education, please contact {contact for education leads}

Once you have been accepted into the pilot program, we will work closely with your school to create accounts for your educators and provide videos, live training, and other resources to help them get the most out of their Screenleap experience.

Sincerely,

Leah Williamson
Director of Customer Success
Screenleap, Inc.
540 University Ave, Suite 250
Palo Alto, CA 94301
support@screenleap.com

Screen sharing with installation-free viewing on all devices:
http://www.screenleap.com/education

**Comment by tuyentruong** [comment]
Final version: https://www.notion.so/screenleap/Early-Reach-Out-letter-932e2f16368a4b96aa45b0271d0bf78d
