### ISSUE TITLE
Feature request: Add feature to annotate live screen shares

### ISSUE THREAD

**Issue by LeahW** [Screenleap/support#88]
Description: An extension user with a Basic subscription has requested the ability to draw and highlight during a live screen share and have this be viewable to the viewer, similar to the ability to annotate captured screenshots.

Additional notes: I advised user that any highlighting they do with their mouse that is visible to them on screen will also be seen by the viewer along with mouse cursor movements.

**Comment by danieldechert** [comment]
Here is a recording I did of the Zoom annotation. [https://drive.google.com/file/d/1Ruwy36cvDBdlY27A02SKK_PsQhtQR2ij/view?usp=sharing]

I don't think we need everything. To be able to draw, spotlight are the 2 most used.

**Comment by LeahW** [comment]
Another user requested this, "I really want to see that as option in my installed as well as in sign in version of screenshare (like alongwith chat/record icons ) to mark my screen and explain things to my clients"

**Comment by tuyentruong** [comment]
Dupicate of Screenleap/screenleap#6300
